/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_corejava_chapter12_61_Printf3 */

#ifndef _Included_com_corejava_chapter12_61_Printf3
#define _Included_com_corejava_chapter12_61_Printf3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_corejava_chapter12_61_Printf3
 * Method:    fprint
 * Signature: (Ljava/io/PrintWriter;Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_corejava_chapter12_161_Printf3_fprint
  (JNIEnv *, jclass, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
