/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_corejava_chapter12_2_MyPrintf */

#ifndef _Included_com_corejava_chapter12_2_MyPrintf
#define _Included_com_corejava_chapter12_2_MyPrintf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_corejava_chapter12_2_MyPrintf
 * Method:    print
 * Signature: (IID)I
 */
JNIEXPORT jint JNICALL Java_com_corejava_chapter12_12_MyPrintf_print
  (JNIEnv *, jclass, jint, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
