/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_corejava_chapter12_4_Employee */

#ifndef _Included_com_corejava_chapter12_4_Employee
#define _Included_com_corejava_chapter12_4_Employee
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_corejava_chapter12_4_Employee
 * Method:    raiseSalary
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_corejava_chapter12_14_Employee_raiseSalary
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
